# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_card.ipynb.

# %% auto 0
__all__ = ['ranks', 'suits', 'Card']

# %% ../00_card.ipynb 2
from fastcore.all import *
import random

# %% ../00_card.ipynb 3
ranks = [None, "A"] + [str(x) for x in range(2,11)] + ["J", "Q", "K"]
suits = ["c","d","h","s"]

# %% ../00_card.ipynb 12
class Card:
    "A playing card"
    def __init__(self, 
                 suit:int,  # An index into `suits`
                 rank:int): # An index into `ranks`
        self.suit,self.rank = suit,rank
    def __str__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__ = __str__
    

# %% ../00_card.ipynb 17
@patch
def __eq__(self:Card, a:Card): return (self.suit,self.rank)==(a.suit,a.rank)
@patch
def __lt__(self:Card, a:Card): return (self.suit,self.rank)<(a.suit,a.rank)
@patch
def __gt__(self:Card, a:Card): return (self.suit,self.rank)>(a.suit,a.rank)
